### ISSUE TITLE
License Violation 

### ISSUE THREAD

**Issue by neechalkaran** [Tamil-Virtual-Academy/Tamilinaiya-Spellchecker#1]
Please provide proper attribution to the code. License file is missing from source location.
http://www.tamilvu.org/sites/default/files/tamil-computing-tools/Aug_2020/Tamilinaiyam%20%20-%20Pizhaithiruthi.zip

**Comment by tshrinivasan** [comment]
There is no violation.

1.
The original TVA page link http://www.tamilvu.org/ta/content/%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AF%8D%E0%AE%95%E0%AF%8D-%E0%AE%95%E0%AE%A3%E0%AE%BF%E0%AE%A9%E0%AE%BF%E0%AE%95%E0%AF%8D-%E0%AE%95%E0%AE%B0%E0%AF%81%E0%AE%B5%E0%AE%BF%E0%AE%95%E0%AE%B3%E0%AF%8D 

for getting the software sourcecode.

2.
License : GPL V2 

Are provided on the README file.

The license.txt is added to the source file two days back only. 
There is no announcement on the TVA site, as the licence.txt file is added to a zip file of the source code.

license.txt file  also says same GPL v2.

Anyhow, thanks for bringing to our notice.

Added the license.txt to the repo and direct download link in the README file.
